= Solution Patterns: Template Name
:page-layout: home
:sectnums:
:sectlinks:
:doctype: book

This solution pattern showcases an architecture which is scalable and efficient system capturing and responding to streaming data using Kafka as the streaming platform and AIML.  With Event-Driven Architecture this system can connect to, and consume from a number of systems, services and data sources by responding to triggering events.


This architecture demonstrates how an Event-Driven Architecture with Red Hat AMQ Streams and OpenShift Serverless can help build an intelligent system with OpenShift Data Science platform to drive business insights and drive an event-driven workflow.

include::content-overview.adoc[]

[#use-cases]
== Use cases

Common use cases that can be address with this architecture are:

- Machine Learning and Real-Time Analytics to build business intelligence 
- Fraud Detection in financial institutions
- Personalized Recommendations
- Forecasting demand
- Image and Video Analysis for object detection, monitoring, face recognition
- Sentiment analysis

include::01-pattern.adoc[]

== Explore more solution patterns
include::https://raw.githubusercontent.com/redhat-solution-patterns/redhat-solution-patterns.github.io/master/documentation/modules/ROOT/pages/solution-pattern-list.adoc[]
